export const loginPageLogo = "text=Nexora Site Manager"
//export const websiteIdInput = "#website_id"
export const websiteIdInput = "input[name='website_id']"
//export const passwordInput = "input[name='password']"
export const passwordInput = "#password"
export const rememberMeCheckbox = "#rememberMe"
export const forgotPasswordLink = "text=Forgot password?"
export const signInButton = "button:has-text('Sign in')"
export const loginButton = "button[type='submit']"
export const errorLoginMessage = "text=Invalid identifier or password"
